# Generated by Django 4.2.4 on 2023-08-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('departure', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
            ],
        ),
    ]
